title: cd/documentos/GIT/cpf
description: python proyect
template:
  repo: cddocumentosgitcpf-template
  name: cddocumentosgitcpf
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
